# GitHub Actions CI Template for Production Spin-offs
# Copy to .github/workflows/ci.yml in spin-off repos

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.11"

jobs:
  # ============================================
  # QUALITY GATE 1: Unit Tests
  # ============================================
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"

      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=src --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml

  # ============================================
  # QUALITY GATE 2: Reproducibility Tests
  # ============================================
  reproducibility:
    name: Reproducibility Verification
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Verify data checksums
        run: |
          python scripts/verify_data.py

      - name: Run reproducibility tests
        run: |
          python scripts/validate.py --ci

      - name: Check metrics match claims
        run: |
          python scripts/check_metrics.py

      - name: Upload validation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: results/

  # ============================================
  # QUALITY GATE 3: Documentation
  # ============================================
  documentation:
    name: Documentation Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -e ".[docs]"

      - name: Check docstrings
        run: |
          pydocstyle src/

      - name: Build docs (verify no errors)
        run: |
          cd docs && make html

      - name: Check for broken links
        run: |
          python scripts/check_links.py

  # ============================================
  # QUALITY GATE 4: Security & Dependencies
  # ============================================
  security:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install safety pip-audit

      - name: Check for vulnerabilities
        run: |
          pip-audit

      - name: License compliance
        run: |
          pip install pip-licenses
          pip-licenses --fail-on="GPL;LGPL"

  # ============================================
  # QUALITY GATE 5: Code Quality
  # ============================================
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install linters
        run: |
          pip install ruff mypy

      - name: Lint with Ruff
        run: |
          ruff check src/

      - name: Type check with MyPy
        run: |
          mypy src/ --ignore-missing-imports

  # ============================================
  # RELEASE: Only after all gates pass
  # ============================================
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [unit-tests, reproducibility, documentation, security, code-quality]
    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*

  # ============================================
  # NOTIFICATION: Summary report
  # ============================================
  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, reproducibility, documentation, security, code-quality]
    if: always()

    steps:
      - name: Check all gates
        run: |
          echo "## Quality Gate Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Gate | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.unit-tests.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Reproducibility | ${{ needs.reproducibility.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Documentation | ${{ needs.documentation.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security | ${{ needs.security.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Quality | ${{ needs.code-quality.result }} |" >> $GITHUB_STEP_SUMMARY
